python3: can't open file '/root/ProyectoZ/scripts/../nucleo/z_core.py': [Errno 2] No such file or directory
